
import React from 'react';
import { 
  Building2, 
  Truck as TruckIcon, 
  ClipboardList, 
  LayoutDashboard, 
  LogOut, 
  Plus, 
  Trash2, 
  Edit, 
  MapPin,
  Package, 
  ArrowUpDown,
  User as UserIcon,
  Sparkles,
  MessageSquare,
  Mic,
  MicOff,
  Search,
  Zap,
  BrainCircuit,
  X,
  Navigation,
  Fuel,
  Wrench,
  ShieldCheck,
  BarChart3,
  Camera,
  PenTool,
  Star,
  LifeBuoy,
  Settings,
  CheckCircle2
} from 'lucide-react';

export const ICONS = {
  Building: Building2,
  Truck: TruckIcon,
  Logs: ClipboardList,
  Dashboard: LayoutDashboard,
  Logout: LogOut,
  Add: Plus,
  Delete: Trash2,
  Edit: Edit,
  Location: MapPin,
  Material: Package,
  Transfer: ArrowUpDown,
  User: UserIcon,
  AI: Sparkles,
  Chat: MessageSquare,
  Mic: Mic,
  MicOff: MicOff,
  Search: Search,
  Zap: Zap,
  BrainCircuit: BrainCircuit,
  Think: BrainCircuit,
  X: X,
  Close: X, 
  Route: Navigation,
  Fuel: Fuel,
  Maintenance: Wrench,
  Security: ShieldCheck,
  Analytics: BarChart3,
  Camera: Camera,
  Sign: PenTool,
  Star: Star,
  Help: LifeBuoy,
  Settings: Settings,
  Success: CheckCircle2
};

export const COLORS = {
  primary: '#3b82f6',
  secondary: '#10b981',
  danger: '#ef4444',
  warning: '#f59e0b',
  bgDark: '#0f172a',
  glassBg: 'rgba(255, 255, 255, 0.05)',
};
